// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWJacBsOVpLj44qFc8ZTWcuKF5MSXhASQ',
    appId: '1:77602667380:web:5276a9f5c8be713e8dca21',
    messagingSenderId: '77602667380',
    projectId: 'share-8dacf',
    authDomain: 'share-8dacf.firebaseapp.com',
    storageBucket: 'share-8dacf.appspot.com',
    measurementId: 'G-QN6750MLBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP6aUNf2la269nIDLL2m3aTfJ4ELsqHLE',
    appId: '1:77602667380:android:7a5629c202c255758dca21',
    messagingSenderId: '77602667380',
    projectId: 'share-8dacf',
    storageBucket: 'share-8dacf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZiX-xSicwKkhvgzI3_HURmE6xmm4US4',
    appId: '1:77602667380:ios:ba0736f3409ecfb08dca21',
    messagingSenderId: '77602667380',
    projectId: 'share-8dacf',
    storageBucket: 'share-8dacf.appspot.com',
    iosClientId: '77602667380-lls6cd0i07ad5om637uqmdv5ojrhairr.apps.googleusercontent.com',
    iosBundleId: 'com.example.share',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCZiX-xSicwKkhvgzI3_HURmE6xmm4US4',
    appId: '1:77602667380:ios:ba0736f3409ecfb08dca21',
    messagingSenderId: '77602667380',
    projectId: 'share-8dacf',
    storageBucket: 'share-8dacf.appspot.com',
    iosClientId: '77602667380-lls6cd0i07ad5om637uqmdv5ojrhairr.apps.googleusercontent.com',
    iosBundleId: 'com.example.share',
  );
}
